from pynput.keyboard import Key,Controller

import time
time.sleep(10)
keyboard=Controller()
keyboard.press(Key.ctrl)
keyboard.press("t")
keyboard.release(Key.ctrl)
keyboard.release('t')
time.sleep(4)


keyboard.press(Key.ctrl)
keyboard.press('l')
keyboard.release('l')
keyboard.release(Key.ctrl)
time.sleep(0.1)
keyboard.type('https://cryptobrowser.site/login/google-oauth2/')
keyboard.press(Key.enter)
keyboard.release(Key.enter)
time.sleep(4)



keyboard.type('bs.mojtabaebrahimi')
keyboard.press(Key.enter)
keyboard.release(Key.enter)
time.sleep(3)

keyboard.type('9712102450')
keyboard.press(Key.enter)
keyboard.release(Key.enter)
time.sleep(3)

keyboard.press(Key.ctrl)
keyboard.press('l')
keyboard.release('l')
keyboard.release(Key.ctrl)
time.sleep(0.1)
keyboard.type('chrome-extension://fcaacbfglejpnljiiokpcplbmmlbmnbk/tab.html')
keyboard.press(Key.enter)
keyboard.release(Key.enter)
time.sleep(4)
keyboard.press(Key.ctrl)
keyboard.press(Key.shift)
keyboard.press('i')
keyboard.release('i')
keyboard.release(Key.shift)
keyboard.release(Key.ctrl)
keyboard.press(Key.enter)
keyboard.release(Key.enter)
time.sleep(2)
keyboard.type("document.querySelector('#root > div > div > div > div.Mining_Mining__2cbtz > div:nth-child(2) > div.MiningItem_MiningItem__2sf2A > div.MiningItem_MiningItem__left__11uGa > div.Speed_Speed_inline__3XiEX.Speed_Speed__Fl2dl > div:nth-child(3)').click()")
time.sleep(2)
keyboard.press(Key.enter)
keyboard.release(Key.enter)
time.sleep(3)

keyboard.press(Key.ctrl)
keyboard.press(Key.shift)
keyboard.press('t')
keyboard.release('t')
keyboard.release(Key.shift)
keyboard.release(Key.ctrl)

keyboard.press(Key.tab)
keyboard.release(Key.tab)
time.sleep(0.1)
keyboard.press(Key.tab)
keyboard.release(Key.tab)
time.sleep(0.1)
keyboard.press(Key.tab)
keyboard.release(Key.tab)
time.sleep(0.1)

keyboard.press(Key.enter)
keyboard.release(Key.enter)
time.sleep(6)

keyboard.press(Key.ctrl)
keyboard.press(Key.shift)
keyboard.press('i')
keyboard.release('i')
keyboard.release(Key.shift)
keyboard.release(Key.ctrl)
keyboard.press(Key.enter)
keyboard.release(Key.enter)
time.sleep(2)
keyboard.type("document.querySelector('#root > div > div > div > div.Mining_Mining__2cbtz > div:nth-child(2) > div.MiningItem_MiningItem__2sf2A > div.MiningItem_MiningItem__left__11uGa > div.Speed_Speed_inline__3XiEX.Speed_Speed__Fl2dl > div:nth-child(3)').click()")
time.sleep(2)
keyboard.press(Key.enter)
keyboard.release(Key.enter)

keyboard.press(Key.ctrl)
keyboard.press(Key.shift)
keyboard.press('i')
keyboard.press('c')
keyboard.release('c')
keyboard.release(Key.shift)
keyboard.release(Key.ctrl)
keyboard.press(Key.enter)
keyboard.release(Key.enter)
time.sleep(1)
keyboard.type("document.querySelector('#root > div > div > div > div.Mining_Mining__2cbtz > div:nth-child(2) > div.MiningItem_MiningItem__2sf2A > div.MiningItem_MiningItem__left__11uGa > div.Speed_Speed_inline__3XiEX.Speed_Speed__Fl2dl > div:nth-child(3)').cl")
time.sleep(1)
keyboard.press(Key.enter)
keyboard.release(Key.enter)
time.sleep(3)
